"""
Django settings for liveproject project.

Generated by 'django-admin startproject' using Django 1.8.1.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os
import sys
from django.conf.global_settings import TEMPLATE_CONTEXT_PROCESSORS



BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'z1#6litaz4a3p0=*q#vxa$4rch-e@mh01f_*tcko8x+mdc6!)$'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['glacial-bastion-94113.herokuapp.com', 'localhost', '*', '127.0.0.1', '0.0.0.0']


# Application definition

INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'liveupdate',
    'kombu.transport.django',
    'opbeat.contrib.django',
    'oauth2_provider',
    # 'social_auth',
    'social.apps.django_app.default',

)

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'opbeat.contrib.django.middleware.OpbeatAPMMiddleware',
    # 'rollbar.contrib.django.middleware.RollbarNotifierMiddleware',
)

OPBEAT = {
    'ORGANIZATION_ID': '419beab043604b6da4360b71acfe5813',
    'APP_ID': '83626ae470',
    'SECRET_TOKEN': '0671c09a0ee5f47c463ca793bae2e32f3ee48869',
}

ROOT_URLCONF = 'liveproject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

TEMPLATE_CONTEXT_PROCESSORS += (
    'django.core.context_processors.request',
    'social_auth.context_processors.social_auth_by_name_backends',
    'social_auth.context_processors.social_auth_backends',
    'social_auth.context_processors.social_auth_by_type_backends',
    'social_auth.context_processors.social_auth_login_redirect',
    'django.contrib.auth.context_processors.auth',
    'django.core.context_processors.debug',
    'django.core.context_processors.i18n',
    'django.core.context_processors.media',
    'django.core.context_processors.static',
    'django.core.context_processors.tz',
    'django.contrib.messages.context_processors.messages',
    'social.apps.django_app.context_processors.backends',
    'social.apps.django_app.context_processors.login_redirect',
)

WSGI_APPLICATION = 'liveproject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases
#

if sys.platform == 'win32':
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
        }
    }
elif sys.platform == 'linux2':
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql_psycopg2',
            'NAME': 'liveupdate',
        }
    }

#
# #heroku configs
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql_psycopg2',
#         'NAME': 'd12sa18ng59qbd',
#         'USER': 'jtjmzihicddigb',
#         'PASSWORD':'Q2XfgklhLmKVJSZkm3yxtQZWN7',
#         'HOST': 'ec2-54-235-153-179.compute-1.amazonaws.com',
#         'PORT': '',
#     }
# }





# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_URL = '/static/'

STATIC_ROOT = '/static/'

MEDIA_ROOT = '/static/files/'

#
# ROLLBAR = {
#     'access_token': '9c97474ac8264da5bfac76bc73cf2930',
#     'environment': 'development' if DEBUG else 'production',
#     'root': BASE_DIR,
# }
# import rollbar
# rollbar.init(**ROLLBAR)

##https://django-social-auth.readthedocs.org/en/latest/index.html
# AUTHENTICATION_BACKENDS = (
#     'social_auth.backends.twitter.TwitterBackend',
#     'social_auth.backends.facebook.FacebookBackend',
#     'social_auth.backends.google.GoogleOAuthBackend',
#     'social_auth.backends.google.GoogleOAuth2Backend',
#     'social_auth.backends.google.GoogleBackend',
#     'social_auth.backends.yahoo.YahooBackend',
#     'social_auth.backends.browserid.BrowserIDBackend',
#     'social_auth.backends.contrib.linkedin.LinkedinBackend',
#     'social_auth.backends.contrib.disqus.DisqusBackend',
#     'social_auth.backends.contrib.livejournal.LiveJournalBackend',
#     'social_auth.backends.contrib.orkut.OrkutBackend',
#     'social_auth.backends.contrib.foursquare.FoursquareBackend',
#     'social_auth.backends.contrib.github.GithubBackend',
#     'social_auth.backends.contrib.vk.VKOAuth2Backend',
#     'social_auth.backends.contrib.live.LiveBackend',
#     'social_auth.backends.contrib.skyrock.SkyrockBackend',
#     'social_auth.backends.contrib.yahoo.YahooOAuthBackend',
#     'social_auth.backends.contrib.readability.ReadabilityBackend',
#     'social_auth.backends.contrib.fedora.FedoraBackend',
#     'social_auth.backends.OpenIDBackend',
#     'django.contrib.auth.backends.ModelBackend',
# )
#



# TWITTER_CONSUMER_KEY         = ''
# TWITTER_CONSUMER_SECRET      = ''
# FACEBOOK_APP_ID              = ''
# FACEBOOK_API_SECRET          = ''
# LINKEDIN_CONSUMER_KEY        = ''
# LINKEDIN_CONSUMER_SECRET     = ''
# ORKUT_CONSUMER_KEY           = ''
# ORKUT_CONSUMER_SECRET        = ''
# GOOGLE_CONSUMER_KEY          = ''
# GOOGLE_CONSUMER_SECRET       = ''
# GOOGLE_OAUTH2_CLIENT_ID      = ''
# GOOGLE_OAUTH2_CLIENT_SECRET  = ''
# FOURSQUARE_CONSUMER_KEY      = ''
# FOURSQUARE_CONSUMER_SECRET   = ''
# VK_APP_ID                    = ''
# VK_API_SECRET                = ''
# LIVE_CLIENT_ID               = ''
# LIVE_CLIENT_SECRET           = ''
# SKYROCK_CONSUMER_KEY         = ''
# SKYROCK_CONSUMER_SECRET      = ''
# YAHOO_CONSUMER_KEY           = ''
# YAHOO_CONSUMER_SECRET        = ''
# READABILITY_CONSUMER_SECRET  = ''
# READABILITY_CONSUMER_SECRET  = ''


# LOGIN_URL          = '/login-form/'
LOGIN_REDIRECT_URL = '/'
# LOGIN_ERROR_URL    = '/login-error/'

SOCIAL_AUTH_FACEBOOK_KEY = 1039994746066994
SOCIAL_AUTH_FACEBOOK_SECRET = '1607a1864188bcf6fd1c1b67a29a8fcf'


# SOCIAL_AUTH_LOGIN_REDIRECT_URL = '/another-login-url/'
# SOCIAL_AUTH_NEW_USER_REDIRECT_URL = '/new-users-redirect-url/'
# SOCIAL_AUTH_NEW_ASSOCIATION_REDIRECT_URL = '/new-association-redirect-url/'
# SOCIAL_AUTH_DISCONNECT_REDIRECT_URL = '/account-disconnected-redirect-url/'
# SOCIAL_AUTH_BACKEND_ERROR_URL = '/new-error-url/'
# SOCIAL_AUTH_COMPLETE_URL_NAME  = 'socialauth_complete'
# SOCIAL_AUTH_ASSOCIATE_URL_NAME = 'socialauth_associate_complete'
# SOCIAL_AUTH_INACTIVE_USER_URL = '...'
# SOCIAL_AUTH_DEFAULT_USERNAME = 'new_social_auth_user'




AUTHENTICATION_BACKENDS = (
   'social.backends.facebook.FacebookOAuth2',
   'social.backends.google.GoogleOAuth2',
   'social.backends.twitter.TwitterOAuth',
   'django.contrib.auth.backends.ModelBackend',
)